### ISSUE TITLE
MagiskSU not detected as root

### ISSUE THREAD

**Issue by JackTheFlap** [jcgruenhage/PlayMusicExporter#22]
Root is not detected within the app and within the Magisk Manager superuser list.

**Comment by jcgruenhage** [comment]
Root work's for you in other apps?

**Comment by JackTheFlap** [comment]
Just fixed the issue, re-flashing Magisk and now it works. Not sure if an older version was to blame.

**Comment by jcgruenhage** [comment]
Well, the app just stopped successfully getting root for me too under MagiskSU too, so this will stay open for now.

**Comment by jcgruenhage** [comment]
The strangest thing about this, is that it doesn't deny root access either, it just times out. After some time, the app throws a NoSuperUserException, which doesn't cause the CrashHandler to start (even more strange). Some logs:
```
03-24 16:11:49.783 31655-31655/re.jcg.playmusicexporter I/art: Late-enabling -Xcheck:jni
03-24 16:11:49.837 31655-31655/re.jcg.playmusicexporter W/System: ClassLoader referenced unknown path: /data/app/re.jcg.playmusicexporter-1/lib/arm64
03-24 16:11:49.874 31655-31655/re.jcg.playmusicexporter W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
03-24 16:11:50.029 31655-31671/re.jcg.playmusicexporter I/Adreno: QUALCOMM build                   : 853a1ff, I9c435c2712
                                                                  Build Date                       : 01/10/17
                                                                  OpenGL ES Shader Compiler Version: XE031.09.00.04
                                                                  Local Branch                     : 
                                                                  Remote Branch                    : 
                                                                  Remote Branch                    : 
                                                                  Reconstruct Branch               : 
03-24 16:11:50.033 31655-31671/re.jcg.playmusicexporter I/OpenGLRenderer: Initialized EGL, version 1.4
03-24 16:11:50.033 31655-31671/re.jcg.playmusicexporter D/OpenGLRenderer: Swap behavior 1
03-24 16:11:50.050 31655-31655/re.jcg.playmusicexporter I/PME_Intro: Fragment switched from {} to {AppIntroFragment{f6810aa #0 id=0x7f0e009b android:switcher:2131624091:0}}.
03-24 16:11:51.749 31655-31655/re.jcg.playmusicexporter I/PME_Intro: Fragment switched from {AppIntroFragment{f6810aa #0 id=0x7f0e009b android:switcher:2131624091:0}} to {AppIntroFragment{3fd7f7c #1 id=0x7f0e009b android:switcher:2131624091:1}}.
03-24 16:11:52.611 31655-31655/re.jcg.playmusicexporter I/PME_Intro: Fragment switched from {AppIntroFragment{3fd7f7c #1 id=0x7f0e009b android:switcher:2131624091:1}} to {AppIntroFragment{2593475 #2 id=0x7f0e009b android:switcher:2131624091:2}}.
03-24 16:11:54.171 31655-31655/re.jcg.playmusicexporter I/PME_Intro: Fragment switched from {AppIntroFragment{2593475 #2 id=0x7f0e009b android:switcher:2131624091:2}} to {AppIntroFragment{53422d4 #3 id=0x7f0e009b android:switcher:2131624091:3}}.
03-24 16:11:55.897 31655-31655/re.jcg.playmusicexporter I/PME_Intro: Fragment switched from {AppIntroFragment{53422d4 #3 id=0x7f0e009b android:switcher:2131624091:3}} to {AppIntroFragment{f6b2f58 #4 id=0x7f0e009b android:switcher:2131624091:4}}.
03-24 16:11:55.904 31655-31683/re.jcg.playmusicexporter I/SuperUser: askForPermissions
03-24 16:11:55.905 31655-31683/re.jcg.playmusicexporter I/SuperUser: < echo 'root'
03-24 16:11:56.823 31655-31655/re.jcg.playmusicexporter I/PME_Intro: Fragment switched from {AppIntroFragment{f6b2f58 #4 id=0x7f0e009b android:switcher:2131624091:4}} to {}.
03-24 16:11:56.967 31655-31655/re.jcg.playmusicexporter W/aymusicexporter: type=1400 audit(0.0:479): avc: denied { getattr } for path="/mnt/media_rw" dev="tmpfs" ino=15621 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:mnt_media_rw_file:s0 tclass=dir permissive=0
03-24 16:11:56.967 31655-31655/re.jcg.playmusicexporter W/aymusicexporter: type=1400 audit(0.0:480): avc: denied { getattr } for path="/mnt/media_rw" dev="tmpfs" ino=15621 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:mnt_media_rw_file:s0 tclass=dir permissive=0
03-24 16:11:57.100 31655-31660/re.jcg.playmusicexporter I/art: Do partial code cache collection, code=25KB, data=29KB
03-24 16:11:57.100 31655-31660/re.jcg.playmusicexporter I/art: After code cache collection, code=25KB, data=29KB
03-24 16:11:57.100 31655-31660/re.jcg.playmusicexporter I/art: Increasing code cache capacity to 128KB
03-24 16:12:25.910 31655-31686/re.jcg.playmusicexporter W/art: Long monitor contention with owner AsyncTask #1 (31683) at void java.lang.Thread.sleep!(java.lang.Object, long, int)(Thread.java:-2) waiters=0 in void java.lang.UNIXProcess.processExited(int) for 29.959s
03-24 16:12:25.911 31655-31655/re.jcg.playmusicexporter W/art: Long monitor contention with owner AsyncTask #1 (31683) at void java.lang.Thread.sleep!(java.lang.Object, long, int)(Thread.java:-2) waiters=1 in int java.lang.UNIXProcess.exitValue() for 28.940s
03-24 16:12:25.918 31655-31655/re.jcg.playmusicexporter I/SuperUser: askForPermissions
03-24 16:12:25.920 31655-31655/re.jcg.playmusicexporter I/SuperUser: < echo 'root'
03-24 16:12:55.923 31655-31655/re.jcg.playmusicexporter E/SetupPlayMusicExporter: de.arcus.playmusiclib.exceptions.NoSuperUserException
03-24 16:12:55.923 31655-31686/re.jcg.playmusicexporter W/art: Long monitor contention with owner main (31655) at void java.lang.Thread.sleep!(java.lang.Object, long, int)(Thread.java:-2) waiters=0 in void java.lang.UNIXProcess.processExited(int) for 29.962s
03-24 16:13:06.574 31655-31655/re.jcg.playmusicexporter I/SuperUser: askForPermissions
03-24 16:13:06.574 31655-31655/re.jcg.playmusicexporter I/SuperUser: < echo 'root'
03-24 16:13:36.575 31655-31686/re.jcg.playmusicexporter W/art: Long monitor contention with owner main (31655) at void java.lang.Thread.sleep!(java.lang.Object, long, int)(Thread.java:-2) waiters=0 in void java.lang.UNIXProcess.processExited(int) for 29.982s
03-24 16:13:36.586 31655-31655/re.jcg.playmusicexporter W/System.err: de.arcus.playmusiclib.exceptions.NoSuperUserException
03-24 16:13:36.587 31655-31655/re.jcg.playmusicexporter W/System.err:     at de.arcus.playmusiclib.PlayMusicManager.loadDatabase(PlayMusicManager.java:354)
03-24 16:13:36.587 31655-31655/re.jcg.playmusicexporter W/System.err:     at de.arcus.playmusiclib.PlayMusicManager.reloadDatabase(PlayMusicManager.java:378)
03-24 16:13:36.587 31655-31655/re.jcg.playmusicexporter W/System.err:     at re.jcg.playmusicexporter.activities.MusicContainerListActivity.lambda$-re_jcg_playmusicexporter_activities_MusicContainerListActivity_lambda$2(MusicContainerListActivity.java:336)
03-24 16:13:36.587 31655-31655/re.jcg.playmusicexporter W/System.err:     at re.jcg.playmusicexporter.activities.-$Lambda$9.$m$0(Unknown Source)
03-24 16:13:36.587 31655-31655/re.jcg.playmusicexporter W/System.err:     at re.jcg.playmusicexporter.activities.-$Lambda$9.onMenuItemClick(Unknown Source)
03-24 16:13:36.587 31655-31655/re.jcg.playmusicexporter W/System.err:     at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
03-24 16:13:36.587 31655-31655/re.jcg.playmusicexporter W/System.err:     at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:969)
03-24 16:13:36.587 31655-31655/re.jcg.playmusicexporter W/System.err:     at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:959)
03-24 16:13:36.587 31655-31655/re.jcg.playmusicexporter W/System.err:     at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:623)
03-24 16:13:36.587 31655-31655/re.jcg.playmusicexporter W/System.err:     at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:154)
03-24 16:13:36.587 31655-31655/re.jcg.playmusicexporter W/System.err:     at android.view.View.performClick(View.java:5637)
03-24 16:13:36.587 31655-31655/re.jcg.playmusicexporter W/System.err:     at android.view.View$PerformClick.run(View.java:22433)
03-24 16:13:36.587 31655-31655/re.jcg.playmusicexporter W/System.err:     at android.os.Handler.handleCallback(Handler.java:751)
03-24 16:13:36.587 31655-31655/re.jcg.playmusicexporter W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
03-24 16:13:36.587 31655-31655/re.jcg.playmusicexporter W/System.err:     at android.os.Looper.loop(Looper.java:154)
03-24 16:13:36.587 31655-31655/re.jcg.playmusicexporter W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6126)
03-24 16:13:36.587 31655-31655/re.jcg.playmusicexporter W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
03-24 16:13:36.587 31655-31655/re.jcg.playmusicexporter W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
03-24 16:13:36.587 31655-31655/re.jcg.playmusicexporter W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
03-24 16:13:36.591 31655-31655/re.jcg.playmusicexporter I/Choreographer: Skipped 1800 frames!  The application may be doing too much work on its main thread.
```

**Comment by jcgruenhage** [comment]
I'll move this to v1.0.0, since it currently works fine for me, and I haven't had any new reports.

**Comment by jcgruenhage** [comment]
Not relevant anymore I guess, no new reports in a while, works fine for me.
